// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWjgUN_jPdszKj8jLANqFDKXjFX6kb88s',
    appId: '1:173070264828:web:1f56aeb40c58efaef6aa79',
    messagingSenderId: '173070264828',
    projectId: 'login-e8324',
    authDomain: 'login-e8324.firebaseapp.com',
    databaseURL: 'https://login-e8324-default-rtdb.firebaseio.com',
    storageBucket: 'login-e8324.appspot.com',
    measurementId: 'G-81YWRZLP61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoxtzUZ8Qi9k2B5WOxv92BFwYX0rx-y48',
    appId: '1:173070264828:android:10309ee4a7b1088ef6aa79',
    messagingSenderId: '173070264828',
    projectId: 'login-e8324',
    databaseURL: 'https://login-e8324-default-rtdb.firebaseio.com',
    storageBucket: 'login-e8324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO_mEzspgwbWdcPyjKe6pdNw5H4baKxu0',
    appId: '1:173070264828:ios:ef10026929ee7387f6aa79',
    messagingSenderId: '173070264828',
    projectId: 'login-e8324',
    databaseURL: 'https://login-e8324-default-rtdb.firebaseio.com',
    storageBucket: 'login-e8324.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO_mEzspgwbWdcPyjKe6pdNw5H4baKxu0',
    appId: '1:173070264828:ios:cceffc5ce2d69f3cf6aa79',
    messagingSenderId: '173070264828',
    projectId: 'login-e8324',
    databaseURL: 'https://login-e8324-default-rtdb.firebaseio.com',
    storageBucket: 'login-e8324.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
